import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyDialog from "@/components/Dialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello",
  description: "Generated by Nghi mimi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
        <MyDialog />
      </body>
    </html>
  );
}
