import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyDialog from "../components/Dialog";
import { ProviderSession } from "@/context/SessionProvider";
import { InitializeSocketConnection } from "@/hooks/InitializeSocketConnection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello",
  description: "Generated by Nghi mimi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <InitializeSocketConnection />
      <html lang="en">
        <body className="bg-body-secondary-bg">
          <ProviderSession>
            {children}
            <MyDialog />
          </ProviderSession>
        </body>
      </html>
    </>
  );
}
